version: '3.8'

volumes:
  postgres_data:
  static_value:
  media_value:

services:
  postgres:
    image: postgres:13.3
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.envs/.postgres
  django:
    image: klyaxa/foodgram-backend:latest
    build: ./backend/
    restart: always
    volumes:
      - static_value:/code/staticfiles/
      - media_value:/code/media/
    depends_on:
      - postgres
    env_file:
      - ./.envs/.postgres
      - ./.envs/.django
  # nginx:
  #   image: nginx:1.21.0
  #   restart: always
  #   volumes:
  #     - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ./docs/:/usr/share/nginx/html/api/docs/
  #     - ./frontend/build:/usr/share/nginx/html/
  #     - static_value:/var/html/static/
  #     - media_value:/var/html/media/
  #   ports:
  #     - 443:443
  #     - 80:80
  #   depends_on:
  #     - django
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=Europe/Moscow
      - VALIDATION=http
      - CERTPROVIDER=zerossl
      - EMAIL=nikolay@kiryanov.ru
    env_file:
      - ./.envs/.swag
    volumes:
      - static_value:/config/backend/static/
      - media_value:/config/backend/media/
      - ./docs/:/config/backend/api/docs/
      - ./frontend/build/:/config/www/
      - ./infra/swag_nginx.conf:/config/nginx/site-confs/default
      # - ./swag/config:/config
    ports:
      - 443:443
      - 80:80
    depends_on:
      - django
    restart: unless-stopped
