# Generated by Django 3.2.5 on 2021-08-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210812_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipetag',
            options={'ordering': ['name'], 'verbose_name': 'Тег рецепта', 'verbose_name_plural': 'Теги рецептов'},
        ),
        migrations.RemoveConstraint(
            model_name='recipe',
            name='unique_recipe_by_author',
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('author', 'name'), name='Unique recipe per author'),
        ),
    ]
