# Generated by Django 3.2.5 on 2021-08-15 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210806_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'verbose_name': 'Подписка на пользователя', 'verbose_name_plural': 'Подписки на пользователя'},
        ),
    ]
